### PR TITLE
Add support for Node.js environments

### PR DESCRIPTION
**Pull request by accommodavid**
I thought I'd add this. Also allows you to push this into npm, if you would like to. (`npm publish`)

### CODE REVIEW

**Comment by puckey** [comment]
thanks - could you explain the use case of this for me?

**Comment by accommodavid** [comment]
In server-side JavaScript environments there is no global `document.domain`. Instead, the hostname can be found with `require("os").hostname()`. This addition simply checks if there is a document variable, and if not, it tries to get the domain name from the host itself.

**Comment by accommodavid** [comment]
In addition to this, the package.json means you can instantly publish to the NPM registry so Node.js users can `npm install` this component, since Component is now deprecated

**Comment by puckey** [comment]
In which scenario would I want to check if the hostname of my server is .dev? I am curious how you are using this...

**Comment by accommodavid** [comment]
Oh okay. Example: if I'm developing an application that uses something like an Express server I can test locally and use this to flip some switches for things like absolute paths to APIs. Or for use with React Native, again to have output with absolute urls.

**Comment by puckey** [comment]
But as far as I know require('os').hostname() will not return the domain name of the website – it will return the hostname of your operating system, or am I mistaken? Did you test it? (and as far as I know React Native does not run in the node.js environment, so in any case you wouldn't be able to use this there)

**Comment by accommodavid** [comment]
Oh oops. Twice. I meant React server-side, not Native. And you are right about the hostname. Should I just open a new pull request with just the package.json instead?

**Comment by puckey** [comment]
Yes, that would be great - many thanks!

**Pull request closed without merging**
